//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ServiceModel;

namespace Nadobe.EvidenceSources.ES_BR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://no/brreg/nlagsys/bestsys/ws", ConfigurationName="Nadobe.EvidenceSources.ES_BR.Bestilling")]
    public interface Bestilling
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Nadobe.EvidenceSources.ES_BR.getBestillingsinfoResponse> getBestillingsinfoAsync(Nadobe.EvidenceSources.ES_BR.getBestillingsinfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Nadobe.EvidenceSources.ES_BR.setBestillingResponse> setBestillingAsync(Nadobe.EvidenceSources.ES_BR.setBestillingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBestillingsinfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBestillingsinfo", Namespace="http://no/brreg/nlagsys/bestsys/ws", Order=0)]
        public Nadobe.EvidenceSources.ES_BR.getBestillingsinfoRequestBody Body;
        
        public getBestillingsinfoRequest()
        {
        }
        
        public getBestillingsinfoRequest(Nadobe.EvidenceSources.ES_BR.getBestillingsinfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://no/brreg/nlagsys/bestsys/ws")]
    public partial class getBestillingsinfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kundenr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ident;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string passord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bestref;
        
        public getBestillingsinfoRequestBody()
        {
        }
        
        public getBestillingsinfoRequestBody(int kundenr, int ident, string passord, string bestref)
        {
            this.kundenr = kundenr;
            this.ident = ident;
            this.passord = passord;
            this.bestref = bestref;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBestillingsinfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBestillingsinfoResponse", Namespace="http://no/brreg/nlagsys/bestsys/ws", Order=0)]
        public Nadobe.EvidenceSources.ES_BR.getBestillingsinfoResponseBody Body;
        
        public getBestillingsinfoResponse()
        {
        }
        
        public getBestillingsinfoResponse(Nadobe.EvidenceSources.ES_BR.getBestillingsinfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://no/brreg/nlagsys/bestsys/ws")]
    public partial class getBestillingsinfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getBestillingsinfoResponseBody()
        {
        }
        
        public getBestillingsinfoResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setBestillingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setBestilling", Namespace="http://no/brreg/nlagsys/bestsys/ws", Order=0)]
        public Nadobe.EvidenceSources.ES_BR.setBestillingRequestBody Body;
        
        public setBestillingRequest()
        {
        }
        
        public setBestillingRequest(Nadobe.EvidenceSources.ES_BR.setBestillingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://no/brreg/nlagsys/bestsys/ws")]
    public partial class setBestillingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kundenr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ident;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string passord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xml;
        
        public setBestillingRequestBody()
        {
        }
        
        public setBestillingRequestBody(int kundenr, int ident, string passord, string xml)
        {
            this.kundenr = kundenr;
            this.ident = ident;
            this.passord = passord;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setBestillingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setBestillingResponse", Namespace="http://no/brreg/nlagsys/bestsys/ws", Order=0)]
        public Nadobe.EvidenceSources.ES_BR.setBestillingResponseBody Body;
        
        public setBestillingResponse()
        {
        }
        
        public setBestillingResponse(Nadobe.EvidenceSources.ES_BR.setBestillingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://no/brreg/nlagsys/bestsys/ws")]
    public partial class setBestillingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public setBestillingResponseBody()
        {
        }
        
        public setBestillingResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface BestillingChannel : Nadobe.EvidenceSources.ES_BR.Bestilling, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class BestillingClient : System.ServiceModel.ClientBase<Nadobe.EvidenceSources.ES_BR.Bestilling>, Nadobe.EvidenceSources.ES_BR.Bestilling
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BestillingClient() : 
                base(BestillingClient.GetDefaultBinding(), BestillingClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BestillingSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BestillingClient(EndpointConfiguration endpointConfiguration) : 
                base(BestillingClient.GetBindingForEndpoint(endpointConfiguration), BestillingClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BestillingClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BestillingClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BestillingClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BestillingClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BestillingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Nadobe.EvidenceSources.ES_BR.getBestillingsinfoResponse> getBestillingsinfoAsync(Nadobe.EvidenceSources.ES_BR.getBestillingsinfoRequest request)
        {
            return base.Channel.getBestillingsinfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nadobe.EvidenceSources.ES_BR.setBestillingResponse> setBestillingAsync(Nadobe.EvidenceSources.ES_BR.setBestillingRequest request)
        {
            return base.Channel.setBestillingAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BestillingSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BestillingSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.brreg.no/nlagsys/bestsysws/Bestilling");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BestillingClient.GetBindingForEndpoint(EndpointConfiguration.BestillingSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BestillingClient.GetEndpointAddress(EndpointConfiguration.BestillingSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            BestillingSoapPort,
        }
    }
}
