//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR_productsservice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", ConfigurationName="BR_productsservice.Products")]
    public interface Products
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ws.oa.nlagsys.brreg.no/Products/getPersonRequest", ReplyAction="http://services.ws.oa.nlagsys.brreg.no/Products/getPersonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BR_productsservice.getPersonResponse> getPersonAsync(BR_productsservice.getPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ws.oa.nlagsys.brreg.no/Products/getEnhetRequest", ReplyAction="http://services.ws.oa.nlagsys.brreg.no/Products/getEnhetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BR_productsservice.getEnhetResponse> getEnhetAsync(BR_productsservice.getEnhetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ws.oa.nlagsys.brreg.no/Products/getProductListRequest", ReplyAction="http://services.ws.oa.nlagsys.brreg.no/Products/getProductListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BR_productsservice.getProductListResponse> getProductListAsync(BR_productsservice.getProductListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ws.oa.nlagsys.brreg.no/Products/orderProductsRequest", ReplyAction="http://services.ws.oa.nlagsys.brreg.no/Products/orderProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BR_productsservice.orderProductsResponse> orderProductsAsync(BR_productsservice.orderProductsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class person
    {
        
        private string adresse1Field;
        
        private string adresse2Field;
        
        private string adresse3Field;
        
        private string fnrField;
        
        private string fornavnField;
        
        private string landkodeField;
        
        private string mellomnavnField;
        
        private string postnrField;
        
        private string poststedField;
        
        private string slektsnavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adresse1
        {
            get
            {
                return this.adresse1Field;
            }
            set
            {
                this.adresse1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adresse2
        {
            get
            {
                return this.adresse2Field;
            }
            set
            {
                this.adresse2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string adresse3
        {
            get
            {
                return this.adresse3Field;
            }
            set
            {
                this.adresse3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fnr
        {
            get
            {
                return this.fnrField;
            }
            set
            {
                this.fnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fornavn
        {
            get
            {
                return this.fornavnField;
            }
            set
            {
                this.fornavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string landkode
        {
            get
            {
                return this.landkodeField;
            }
            set
            {
                this.landkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mellomnavn
        {
            get
            {
                return this.mellomnavnField;
            }
            set
            {
                this.mellomnavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string postnr
        {
            get
            {
                return this.postnrField;
            }
            set
            {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string poststed
        {
            get
            {
                return this.poststedField;
            }
            set
            {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string slektsnavn
        {
            get
            {
                return this.slektsnavnField;
            }
            set
            {
                this.slektsnavnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class productProduced
    {
        
        private string uRLField;
        
        private int accountingYearField;
        
        private string bestrefField;
        
        private int codeField;
        
        private int deliveryMethodField;
        
        private int lnrField;
        
        private string nameField;
        
        private bool productionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int accountingYear
        {
            get
            {
                return this.accountingYearField;
            }
            set
            {
                this.accountingYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string bestref
        {
            get
            {
                return this.bestrefField;
            }
            set
            {
                this.bestrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int deliveryMethod
        {
            get
            {
                return this.deliveryMethodField;
            }
            set
            {
                this.deliveryMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int lnr
        {
            get
            {
                return this.lnrField;
            }
            set
            {
                this.lnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool productionStatus
        {
            get
            {
                return this.productionStatusField;
            }
            set
            {
                this.productionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class productImpl
    {
        
        private int accountYearField;
        
        private int codeField;
        
        private int deliveryMethodField;
        
        private int deliveryUnitField;
        
        private string nameField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int accountYear
        {
            get
            {
                return this.accountYearField;
            }
            set
            {
                this.accountYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int deliveryMethod
        {
            get
            {
                return this.deliveryMethodField;
            }
            set
            {
                this.deliveryMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int deliveryUnit
        {
            get
            {
                return this.deliveryUnitField;
            }
            set
            {
                this.deliveryUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string system
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class status
    {
        
        private int hovedstatusField;
        
        private System.Nullable<int>[] underStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hovedstatus
        {
            get
            {
                return this.hovedstatusField;
            }
            set
            {
                this.hovedstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("underStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int>[] underStatus
        {
            get
            {
                return this.underStatusField;
            }
            set
            {
                this.underStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class postadresse
    {
        
        private string adresse1Field;
        
        private string adresse2Field;
        
        private string adresse3Field;
        
        private string landField;
        
        private string postnummerField;
        
        private string poststedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adresse1
        {
            get
            {
                return this.adresse1Field;
            }
            set
            {
                this.adresse1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adresse2
        {
            get
            {
                return this.adresse2Field;
            }
            set
            {
                this.adresse2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string adresse3
        {
            get
            {
                return this.adresse3Field;
            }
            set
            {
                this.adresse3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string land
        {
            get
            {
                return this.landField;
            }
            set
            {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string postnummer
        {
            get
            {
                return this.postnummerField;
            }
            set
            {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string poststed
        {
            get
            {
                return this.poststedField;
            }
            set
            {
                this.poststedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class forretningsadresse
    {
        
        private string adresse1Field;
        
        private string adresse2Field;
        
        private string adresse3Field;
        
        private string landField;
        
        private string postnummerField;
        
        private string poststedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adresse1
        {
            get
            {
                return this.adresse1Field;
            }
            set
            {
                this.adresse1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adresse2
        {
            get
            {
                return this.adresse2Field;
            }
            set
            {
                this.adresse2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string adresse3
        {
            get
            {
                return this.adresse3Field;
            }
            set
            {
                this.adresse3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string land
        {
            get
            {
                return this.landField;
            }
            set
            {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string postnummer
        {
            get
            {
                return this.postnummerField;
            }
            set
            {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string poststed
        {
            get
            {
                return this.poststedField;
            }
            set
            {
                this.poststedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/")]
    public partial class enhetData
    {
        
        private forretningsadresse forretningadrField;
        
        private string navn1Field;
        
        private string navn2Field;
        
        private string navn3Field;
        
        private string navn4Field;
        
        private string navn5Field;
        
        private string orgdescField;
        
        private string orgkodeField;
        
        private string orgnrField;
        
        private postadresse postadrField;
        
        private status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public forretningsadresse forretningadr
        {
            get
            {
                return this.forretningadrField;
            }
            set
            {
                this.forretningadrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string navn1
        {
            get
            {
                return this.navn1Field;
            }
            set
            {
                this.navn1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string navn2
        {
            get
            {
                return this.navn2Field;
            }
            set
            {
                this.navn2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string navn3
        {
            get
            {
                return this.navn3Field;
            }
            set
            {
                this.navn3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string navn4
        {
            get
            {
                return this.navn4Field;
            }
            set
            {
                this.navn4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string navn5
        {
            get
            {
                return this.navn5Field;
            }
            set
            {
                this.navn5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orgdesc
        {
            get
            {
                return this.orgdescField;
            }
            set
            {
                this.orgdescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string orgkode
        {
            get
            {
                return this.orgkodeField;
            }
            set
            {
                this.orgkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string orgnr
        {
            get
            {
                return this.orgnrField;
            }
            set
            {
                this.orgnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public postadresse postadr
        {
            get
            {
                return this.postadrField;
            }
            set
            {
                this.postadrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public status status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPerson", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class getPersonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fnr;
        
        public getPersonRequest()
        {
        }
        
        public getPersonRequest(string fnr)
        {
            this.fnr = fnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonResponse", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class getPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BR_productsservice.person @return;
        
        public getPersonResponse()
        {
        }
        
        public getPersonResponse(BR_productsservice.person @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnhet", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class getEnhetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgnr;
        
        public getEnhetRequest()
        {
        }
        
        public getEnhetRequest(string orgnr)
        {
            this.orgnr = orgnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnhetResponse", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class getEnhetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BR_productsservice.enhetData @return;
        
        public getEnhetResponse()
        {
        }
        
        public getEnhetResponse(BR_productsservice.enhetData @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductList", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class getProductListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgnr;
        
        public getProductListRequest()
        {
        }
        
        public getProductListRequest(string orgnr)
        {
            this.orgnr = orgnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductListResponse", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class getProductListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BR_productsservice.productImpl[] @return;
        
        public getProductListResponse()
        {
        }
        
        public getProductListResponse(BR_productsservice.productImpl[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="orderProducts", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class orderProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enhetsnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("products", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BR_productsservice.productImpl[] products;
        
        public orderProductsRequest()
        {
        }
        
        public orderProductsRequest(string enhetsnr, string language, BR_productsservice.productImpl[] products)
        {
            this.enhetsnr = enhetsnr;
            this.language = language;
            this.products = products;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="orderProductsResponse", WrapperNamespace="http://services.ws.oa.nlagsys.brreg.no/", IsWrapped=true)]
    public partial class orderProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ws.oa.nlagsys.brreg.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BR_productsservice.productProduced[] @return;
        
        public orderProductsResponse()
        {
        }
        
        public orderProductsResponse(BR_productsservice.productProduced[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ProductsChannel : BR_productsservice.Products, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ProductsClient : System.ServiceModel.ClientBase<BR_productsservice.Products>, BR_productsservice.Products
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductsClient() : 
                base(ProductsClient.GetDefaultBinding(), ProductsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProductsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductsClient.GetBindingForEndpoint(endpointConfiguration), ProductsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BR_productsservice.getPersonResponse> getPersonAsync(BR_productsservice.getPersonRequest request)
        {
            return base.Channel.getPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<BR_productsservice.getEnhetResponse> getEnhetAsync(BR_productsservice.getEnhetRequest request)
        {
            return base.Channel.getEnhetAsync(request);
        }
        
        public System.Threading.Tasks.Task<BR_productsservice.getProductListResponse> getProductListAsync(BR_productsservice.getProductListRequest request)
        {
            return base.Channel.getProductListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BR_productsservice.orderProductsResponse> orderProductsAsync(BR_productsservice.orderProductsRequest request)
        {
            return base.Channel.orderProductsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductsPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductsPort))
            {
                return new System.ServiceModel.EndpointAddress("https://wss.brreg.no/OAWS/ProductsService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProductsClient.GetBindingForEndpoint(EndpointConfiguration.ProductsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProductsClient.GetEndpointAddress(EndpointConfiguration.ProductsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProductsPort,
        }
    }
}
